//				[!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!]
//							NOTE: THIS FILE IS GENERATED BY subthemes
//						CHANGES SHOULD BE COMMITED BY THE METHOD DOCUMENTED IN subthemes 
//				[!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!]  


//  {$mag} variables
//  -----------------------------
//
//  Table of Contents:
//
//   0. Base theme settings
//   1. Logo
//   2. Colours
//   3. Typography

//				[!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!]
//							NOTE: THIS FILE IS GENERATED BY subthemes
//						CHANGES SHOULD BE COMMITED BY THE METHOD DOCUMENTED IN subthemes 
//				[!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!][!]  


// 0. Base theme settings (won't vary per mag)
// ---------
$breakpoint-small: 0;
$breakpoint-medium: 640px;
$breakpoint-large: 1025px;
$breakpoint-xlarge: 1285px;
$breakpoint-xxlarge: 1440px;

$margin-small: 0.5rem;

// 1. Logo
// ---------
$logo-url: url({$smarty.config.logoURL});
$logo-mobile-url: url({$smarty.config.logoURL});
$logo-header-width-small: {$smarty.config.logoSmallW};
$logo-header-height-small: {$smarty.config.logoSmallH};
$logo-header-width-medium: {$smarty.config.logoMedW};
$logo-header-height-medium: {$smarty.config.logoMedH};
$logo-header-width-large: {$smarty.config.logoLargeW};
$logo-header-height-large: {$smarty.config.logoLargeH};

// 2. Colours
// ---------
$primary-color: {$smarty.config.priCol};
$secondary-color: {$smarty.config.secCol};
$light-gray: {$smarty.config.grayLight};
$medium-gray: {$smarty.config.grayMed};
$dark-gray: {$smarty.config.grayDark};
$light-grey: $light-gray;
$medium-grey: $medium-gray;
$dark-grey: $dark-gray;
$black: {$smarty.config.black};
$white: {$smarty.config.white};
$shadedViewsBackground: {$smarty.config.shadedViewsBackground};

// 3. Typography
// ---------
$anchor-color: {$smarty.config.anchorCol};
$anchor-color-hover: scale-color($anchor-color, $lightness: -14%);
$anchor-text-decoration: none;

// 4. Images
// ---------
$tag-icon-url: url({$smarty.config.tagIconURL});
$access-digital-edition: url({$smarty.config.digEdAccessImageURL});

// 5. Styles

body {
	background-color:$light-gray;
}

#site-logo {
	background-image:$logo-url;
}

.block-nice-menus {
	background-color: {$smarty.config.menuBackgroundCol};
}

ul.nice-menu li.active-trail {
	border-left-color: $primary-color;
}

.breadcrumbs a {
	color:$anchor-color;
}

a {
	color: $anchor-color;
	&:hover, &:focus {
		color: $anchor-color-hover;
	}
}

.button.primary, 
.button.primary:focus, 
.button.primary:hover,
.button:hover,
.button:focus {
	background-color:$primary-color;
}

a.link-to-subindex, .link-to-term-page a {
	border-left-color:$primary-color;
	&:hover {
		border-left-color: darken($primary-color, 1%);
        color: $primary-color;
	}
}

.block footer a.link-to-subindex {
	border-right-color:$primary-color;
}

footer.read-more-subindex a {
	color:$anchor-color;
}

#footer-logo {
    background-repeat:no-repeat;
    background-size:contain;
    background-position:center;
	background-image:$logo-url;
    height: 5rem;
}

#desk-skyscraper-btn-ads .view-events-front .view-content .views-row .views-field-field-dates {
	color:$primary-color;
}

body.page-premium-access .sponsored-content-heading-block,
body.not-front.page-node article.node .sponsored-content-heading-block {
	border-color:$primary-color;
	color:$primary-color;
}

.view-white-papers .views-field-field-tags,
.field-type-taxonomy-term-reference,
.view-promoted-to-front-page .views-field-field-tags {	
	background-image:$tag-icon-url;
}

.field-name-field-call-to-action .field-items .field-item a {
	background-image:$access-digital-edition;
}